### ISSUE TITLE
How were the 64 architectures selected, randomly or carefully? 

### ISSUE THREAD

**Issue by fly2tortoise** [ShunLu91/PA-DA#2]
Dear researcher, I have a few small doubts to ask you.

1. How to choose the 64 architectures, are they random or carefully selected? Were they selected according to a certain ranking arrangement?

2. about the measurement of ktau coefficient, why the Fig. 1(a) is 0.4, while the paper says it is 0.713. Any evaluation rules you can share?

Thank you very much.

**Comment by ShunLu91** [comment]
Hello fly2tortoise, thanks for your interest in our work. Let me clarify these questions for you. 

1. Instead of randomly or carefully selecting the 64 architectures, we first select "nor_conv_1x1" and "nor_conv_3x3" as the candidate operations and then construct the smallest search space including the 64 architectures. Thanks for pointing out this issue, which reminds us of a typo in Fig. 1(a), where GV and KT used the same left Y-axis when plotting the figure. After fixing this issue, the actual Fig. 1(a) is shown as below. When there is only one operation per edge, the KT should be 1.0.
![panda_fig1_0_share_var](https://github.com/ShunLu91/PA-DA/assets/37992509/83100861-c8cf-4c5e-8e53-5fad41d2881e)
2. As for the measurement of KT, we only measure the KT of 64 architectures in Fig. 1(b) to keep it consistent with the Fig. 1(a). However, when comparing with other methods, we measure the KT of all 15625 architectures in Tab.1. 

Sorry for these misleadings and thank you for these constructive suggestions, we will update these details in our next arXiv version.

**Comment by fly2tortoise** [comment]
Thank you very much for your guidance, your work is really excellent.
